
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 29 13:18:27 CET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 10;
  public static final int CHAR = 2;
  public static final int UMINUS = 34;
  public static final int GREATER = 5;
  public static final int INT = 19;
  public static final int LESS = 6;
  public static final int MINUS = 9;
  public static final int WRITE = 12;
  public static final int NOT = 7;
  public static final int SEMICOLON = 30;
  public static final int RPAR = 23;
  public static final int COMMA = 31;
  public static final int EOL = 18;
  public static final int PLUS = 11;
  public static final int ASSIGN = 29;
  public static final int IF = 20;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int LOW = 33;
  public static final int EQUAL = 4;
  public static final int error = 1;
  public static final int NUMBER = 35;
  public static final int NAME = 36;
  public static final int LBRACK = 26;
  public static final int TIMES = 8;
  public static final int LBRACE = 24;
  public static final int ELSE = 21;
  public static final int READ = 13;
  public static final int RBRACK = 27;
  public static final int WHILE = 15;
  public static final int NEQUAL = 3;
  public static final int RBRACE = 25;
  public static final int LPAR = 22;
  public static final int QCHAR = 17;
  public static final int LENGTH = 14;
  public static final int DO = 16;
}

