
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 28 15:00:57 CET 2014
//----------------------------------------------------

package miny_pascal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 7;
  public static final int IDENTICAL = 48;
  public static final int CASE = 45;
  public static final int INTEGER = 9;
  public static final int SEMI = 55;
  public static final int REPEAT = 22;
  public static final int ARRAY = 13;
  public static final int FIN = 47;
  public static final int FOR = 46;
  public static final int WRITE = 27;
  public static final int GRE = 40;
  public static final int NOT = 44;
  public static final int AND = 42;
  public static final int RPAR = 57;
  public static final int RECORD = 11;
  public static final int UMIN = 53;
  public static final int INTCONST = 63;
  public static final int OR = 43;
  public static final int COMMA = 61;
  public static final int FI = 23;
  public static final int DIV = 33;
  public static final int BEGIN = 3;
  public static final int RPAR_SQ = 59;
  public static final int LPAR_SQ = 58;
  public static final int GEQ = 41;
  public static final int MIN = 31;
  public static final int ASSIGN = 15;
  public static final int IF = 18;
  public static final int PTR = 62;
  public static final int DOT = 60;
  public static final int OF = 14;
  public static final int EOF = 0;
  public static final int BOOLEAN = 12;
  public static final int LC = 16;
  public static final int OD = 25;
  public static final int BY = 50;
  public static final int TRUE = 28;
  public static final int NEW = 52;
  public static final int error = 1;
  public static final int RC = 17;
  public static final int PROGRAM = 2;
  public static final int MUL = 32;
  public static final int ADD = 30;
  public static final int MOD = 35;
  public static final int NEQ = 39;
  public static final int IDE = 64;
  public static final int DECLARE = 5;
  public static final int FROM = 49;
  public static final int REAL = 10;
  public static final int EQU = 38;
  public static final int COLON = 54;
  public static final int ELSE = 20;
  public static final int READ = 26;
  public static final int TO = 51;
  public static final int GOTO = 34;
  public static final int WHILE = 21;
  public static final int REALCONST = 65;
  public static final int LES = 36;
  public static final int THEN = 19;
  public static final int LEQ = 37;
  public static final int END = 4;
  public static final int STRING = 66;
  public static final int LPAR = 56;
  public static final int FALSE = 29;
  public static final int LABEL = 8;
  public static final int PROCEDURE = 6;
  public static final int DO = 24;
}

